remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: What Are the Best Predictors of Calories in a Recipe?
description: a project by Nic Colebank
